// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/product/v1/product.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_CreateCategory_FullMethodName     = "/product.v1.ProductService/CreateCategory"
	ProductService_UpdateCategory_FullMethodName     = "/product.v1.ProductService/UpdateCategory"
	ProductService_DeleteCategory_FullMethodName     = "/product.v1.ProductService/DeleteCategory"
	ProductService_GetCategoryTree_FullMethodName    = "/product.v1.ProductService/GetCategoryTree"
	ProductService_CreateBrand_FullMethodName        = "/product.v1.ProductService/CreateBrand"
	ProductService_ListBrands_FullMethodName         = "/product.v1.ProductService/ListBrands"
	ProductService_CreateSPU_FullMethodName          = "/product.v1.ProductService/CreateSPU"
	ProductService_UpdateSPU_FullMethodName          = "/product.v1.ProductService/UpdateSPU"
	ProductService_GetSPU_FullMethodName             = "/product.v1.ProductService/GetSPU"
	ProductService_ListSPUs_FullMethodName           = "/product.v1.ProductService/ListSPUs"
	ProductService_BatchCreateSKU_FullMethodName     = "/product.v1.ProductService/BatchCreateSKU"
	ProductService_UpdateSKU_FullMethodName          = "/product.v1.ProductService/UpdateSKU"
	ProductService_ListSKUs_FullMethodName           = "/product.v1.ProductService/ListSKUs"
	ProductService_LockStock_FullMethodName          = "/product.v1.ProductService/LockStock"
	ProductService_ConfirmDeductStock_FullMethodName = "/product.v1.ProductService/ConfirmDeductStock"
	ProductService_UnlockStock_FullMethodName        = "/product.v1.ProductService/UnlockStock"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProductService is the product management service (categories, brands, SPU, SKU, stock).
type ProductServiceClient interface {
	// Category
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*Empty, error)
	GetCategoryTree(ctx context.Context, in *GetCategoryTreeRequest, opts ...grpc.CallOption) (*GetCategoryTreeResponse, error)
	// Brand
	CreateBrand(ctx context.Context, in *CreateBrandRequest, opts ...grpc.CallOption) (*BrandResponse, error)
	ListBrands(ctx context.Context, in *ListBrandsRequest, opts ...grpc.CallOption) (*ListBrandsResponse, error)
	// SPU
	CreateSPU(ctx context.Context, in *CreateSPURequest, opts ...grpc.CallOption) (*SPUResponse, error)
	UpdateSPU(ctx context.Context, in *UpdateSPURequest, opts ...grpc.CallOption) (*SPUResponse, error)
	GetSPU(ctx context.Context, in *GetSPURequest, opts ...grpc.CallOption) (*SPUResponse, error)
	ListSPUs(ctx context.Context, in *ListSPUsRequest, opts ...grpc.CallOption) (*ListSPUsResponse, error)
	// SKU
	BatchCreateSKU(ctx context.Context, in *BatchCreateSKURequest, opts ...grpc.CallOption) (*BatchCreateSKUResponse, error)
	UpdateSKU(ctx context.Context, in *UpdateSKURequest, opts ...grpc.CallOption) (*SKUResponse, error)
	ListSKUs(ctx context.Context, in *ListSKUsRequest, opts ...grpc.CallOption) (*ListSKUsResponse, error)
	// Stock (核心，供订单服务调用)
	LockStock(ctx context.Context, in *LockStockRequest, opts ...grpc.CallOption) (*LockStockResponse, error)
	ConfirmDeductStock(ctx context.Context, in *ConfirmDeductRequest, opts ...grpc.CallOption) (*Empty, error)
	UnlockStock(ctx context.Context, in *UnlockStockRequest, opts ...grpc.CallOption) (*Empty, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, ProductService_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProductService_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetCategoryTree(ctx context.Context, in *GetCategoryTreeRequest, opts ...grpc.CallOption) (*GetCategoryTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryTreeResponse)
	err := c.cc.Invoke(ctx, ProductService_GetCategoryTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateBrand(ctx context.Context, in *CreateBrandRequest, opts ...grpc.CallOption) (*BrandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrandResponse)
	err := c.cc.Invoke(ctx, ProductService_CreateBrand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListBrands(ctx context.Context, in *ListBrandsRequest, opts ...grpc.CallOption) (*ListBrandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBrandsResponse)
	err := c.cc.Invoke(ctx, ProductService_ListBrands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateSPU(ctx context.Context, in *CreateSPURequest, opts ...grpc.CallOption) (*SPUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SPUResponse)
	err := c.cc.Invoke(ctx, ProductService_CreateSPU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateSPU(ctx context.Context, in *UpdateSPURequest, opts ...grpc.CallOption) (*SPUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SPUResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdateSPU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetSPU(ctx context.Context, in *GetSPURequest, opts ...grpc.CallOption) (*SPUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SPUResponse)
	err := c.cc.Invoke(ctx, ProductService_GetSPU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListSPUs(ctx context.Context, in *ListSPUsRequest, opts ...grpc.CallOption) (*ListSPUsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSPUsResponse)
	err := c.cc.Invoke(ctx, ProductService_ListSPUs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) BatchCreateSKU(ctx context.Context, in *BatchCreateSKURequest, opts ...grpc.CallOption) (*BatchCreateSKUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateSKUResponse)
	err := c.cc.Invoke(ctx, ProductService_BatchCreateSKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateSKU(ctx context.Context, in *UpdateSKURequest, opts ...grpc.CallOption) (*SKUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SKUResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdateSKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListSKUs(ctx context.Context, in *ListSKUsRequest, opts ...grpc.CallOption) (*ListSKUsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSKUsResponse)
	err := c.cc.Invoke(ctx, ProductService_ListSKUs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) LockStock(ctx context.Context, in *LockStockRequest, opts ...grpc.CallOption) (*LockStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockStockResponse)
	err := c.cc.Invoke(ctx, ProductService_LockStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ConfirmDeductStock(ctx context.Context, in *ConfirmDeductRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProductService_ConfirmDeductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UnlockStock(ctx context.Context, in *UnlockStockRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ProductService_UnlockStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
//
// ProductService is the product management service (categories, brands, SPU, SKU, stock).
type ProductServiceServer interface {
	// Category
	CreateCategory(context.Context, *CreateCategoryRequest) (*CategoryResponse, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*CategoryResponse, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*Empty, error)
	GetCategoryTree(context.Context, *GetCategoryTreeRequest) (*GetCategoryTreeResponse, error)
	// Brand
	CreateBrand(context.Context, *CreateBrandRequest) (*BrandResponse, error)
	ListBrands(context.Context, *ListBrandsRequest) (*ListBrandsResponse, error)
	// SPU
	CreateSPU(context.Context, *CreateSPURequest) (*SPUResponse, error)
	UpdateSPU(context.Context, *UpdateSPURequest) (*SPUResponse, error)
	GetSPU(context.Context, *GetSPURequest) (*SPUResponse, error)
	ListSPUs(context.Context, *ListSPUsRequest) (*ListSPUsResponse, error)
	// SKU
	BatchCreateSKU(context.Context, *BatchCreateSKURequest) (*BatchCreateSKUResponse, error)
	UpdateSKU(context.Context, *UpdateSKURequest) (*SKUResponse, error)
	ListSKUs(context.Context, *ListSKUsRequest) (*ListSKUsResponse, error)
	// Stock (核心，供订单服务调用)
	LockStock(context.Context, *LockStockRequest) (*LockStockResponse, error)
	ConfirmDeductStock(context.Context, *ConfirmDeductRequest) (*Empty, error)
	UnlockStock(context.Context, *UnlockStockRequest) (*Empty, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedProductServiceServer) UpdateCategory(context.Context, *UpdateCategoryRequest) (*CategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedProductServiceServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedProductServiceServer) GetCategoryTree(context.Context, *GetCategoryTreeRequest) (*GetCategoryTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryTree not implemented")
}
func (UnimplementedProductServiceServer) CreateBrand(context.Context, *CreateBrandRequest) (*BrandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBrand not implemented")
}
func (UnimplementedProductServiceServer) ListBrands(context.Context, *ListBrandsRequest) (*ListBrandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBrands not implemented")
}
func (UnimplementedProductServiceServer) CreateSPU(context.Context, *CreateSPURequest) (*SPUResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSPU not implemented")
}
func (UnimplementedProductServiceServer) UpdateSPU(context.Context, *UpdateSPURequest) (*SPUResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSPU not implemented")
}
func (UnimplementedProductServiceServer) GetSPU(context.Context, *GetSPURequest) (*SPUResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSPU not implemented")
}
func (UnimplementedProductServiceServer) ListSPUs(context.Context, *ListSPUsRequest) (*ListSPUsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSPUs not implemented")
}
func (UnimplementedProductServiceServer) BatchCreateSKU(context.Context, *BatchCreateSKURequest) (*BatchCreateSKUResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateSKU not implemented")
}
func (UnimplementedProductServiceServer) UpdateSKU(context.Context, *UpdateSKURequest) (*SKUResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSKU not implemented")
}
func (UnimplementedProductServiceServer) ListSKUs(context.Context, *ListSKUsRequest) (*ListSKUsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSKUs not implemented")
}
func (UnimplementedProductServiceServer) LockStock(context.Context, *LockStockRequest) (*LockStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockStock not implemented")
}
func (UnimplementedProductServiceServer) ConfirmDeductStock(context.Context, *ConfirmDeductRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmDeductStock not implemented")
}
func (UnimplementedProductServiceServer) UnlockStock(context.Context, *UnlockStockRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockStock not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetCategoryTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetCategoryTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetCategoryTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetCategoryTree(ctx, req.(*GetCategoryTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateBrand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBrandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateBrand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateBrand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateBrand(ctx, req.(*CreateBrandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListBrands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBrandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListBrands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListBrands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListBrands(ctx, req.(*ListBrandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateSPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSPURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateSPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateSPU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateSPU(ctx, req.(*CreateSPURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateSPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSPURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateSPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdateSPU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateSPU(ctx, req.(*UpdateSPURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetSPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSPURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetSPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetSPU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetSPU(ctx, req.(*GetSPURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListSPUs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSPUsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListSPUs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListSPUs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListSPUs(ctx, req.(*ListSPUsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_BatchCreateSKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateSKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).BatchCreateSKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_BatchCreateSKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).BatchCreateSKU(ctx, req.(*BatchCreateSKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateSKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateSKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdateSKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateSKU(ctx, req.(*UpdateSKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListSKUs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSKUsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListSKUs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListSKUs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListSKUs(ctx, req.(*ListSKUsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_LockStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).LockStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_LockStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).LockStock(ctx, req.(*LockStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ConfirmDeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmDeductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ConfirmDeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ConfirmDeductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ConfirmDeductStock(ctx, req.(*ConfirmDeductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UnlockStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UnlockStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UnlockStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UnlockStock(ctx, req.(*UnlockStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.v1.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategory",
			Handler:    _ProductService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _ProductService_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _ProductService_DeleteCategory_Handler,
		},
		{
			MethodName: "GetCategoryTree",
			Handler:    _ProductService_GetCategoryTree_Handler,
		},
		{
			MethodName: "CreateBrand",
			Handler:    _ProductService_CreateBrand_Handler,
		},
		{
			MethodName: "ListBrands",
			Handler:    _ProductService_ListBrands_Handler,
		},
		{
			MethodName: "CreateSPU",
			Handler:    _ProductService_CreateSPU_Handler,
		},
		{
			MethodName: "UpdateSPU",
			Handler:    _ProductService_UpdateSPU_Handler,
		},
		{
			MethodName: "GetSPU",
			Handler:    _ProductService_GetSPU_Handler,
		},
		{
			MethodName: "ListSPUs",
			Handler:    _ProductService_ListSPUs_Handler,
		},
		{
			MethodName: "BatchCreateSKU",
			Handler:    _ProductService_BatchCreateSKU_Handler,
		},
		{
			MethodName: "UpdateSKU",
			Handler:    _ProductService_UpdateSKU_Handler,
		},
		{
			MethodName: "ListSKUs",
			Handler:    _ProductService_ListSKUs_Handler,
		},
		{
			MethodName: "LockStock",
			Handler:    _ProductService_LockStock_Handler,
		},
		{
			MethodName: "ConfirmDeductStock",
			Handler:    _ProductService_ConfirmDeductStock_Handler,
		},
		{
			MethodName: "UnlockStock",
			Handler:    _ProductService_UnlockStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/product/v1/product.proto",
}
