// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/product/v1/product.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProductErrorReason defines business error codes for the product domain.
type ProductErrorReason int32

const (
	ProductErrorReason_CATEGORY_NOT_FOUND         ProductErrorReason = 0
	ProductErrorReason_CATEGORY_HAS_CHILDREN      ProductErrorReason = 1
	ProductErrorReason_BRAND_NOT_FOUND            ProductErrorReason = 2
	ProductErrorReason_SPU_NOT_FOUND              ProductErrorReason = 3
	ProductErrorReason_SKU_NOT_FOUND              ProductErrorReason = 4
	ProductErrorReason_STOCK_INSUFFICIENT         ProductErrorReason = 5
	ProductErrorReason_STOCK_LOCK_CONFLICT        ProductErrorReason = 6
	ProductErrorReason_STOCK_OPERATION_DUPLICATED ProductErrorReason = 7
	ProductErrorReason_SKU_ATTR_INVALID           ProductErrorReason = 8
	ProductErrorReason_STATUS_TRANSITION_INVALID  ProductErrorReason = 9
)

// Enum value maps for ProductErrorReason.
var (
	ProductErrorReason_name = map[int32]string{
		0: "CATEGORY_NOT_FOUND",
		1: "CATEGORY_HAS_CHILDREN",
		2: "BRAND_NOT_FOUND",
		3: "SPU_NOT_FOUND",
		4: "SKU_NOT_FOUND",
		5: "STOCK_INSUFFICIENT",
		6: "STOCK_LOCK_CONFLICT",
		7: "STOCK_OPERATION_DUPLICATED",
		8: "SKU_ATTR_INVALID",
		9: "STATUS_TRANSITION_INVALID",
	}
	ProductErrorReason_value = map[string]int32{
		"CATEGORY_NOT_FOUND":         0,
		"CATEGORY_HAS_CHILDREN":      1,
		"BRAND_NOT_FOUND":            2,
		"SPU_NOT_FOUND":              3,
		"SKU_NOT_FOUND":              4,
		"STOCK_INSUFFICIENT":         5,
		"STOCK_LOCK_CONFLICT":        6,
		"STOCK_OPERATION_DUPLICATED": 7,
		"SKU_ATTR_INVALID":           8,
		"STATUS_TRANSITION_INVALID":  9,
	}
)

func (x ProductErrorReason) Enum() *ProductErrorReason {
	p := new(ProductErrorReason)
	*p = x
	return p
}

func (x ProductErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_product_v1_product_proto_enumTypes[0].Descriptor()
}

func (ProductErrorReason) Type() protoreflect.EnumType {
	return &file_api_product_v1_product_proto_enumTypes[0]
}

func (x ProductErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductErrorReason.Descriptor instead.
func (ProductErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{0}
}

type CategoryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Children      []*CategoryProto       `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryProto) Reset() {
	*x = CategoryProto{}
	mi := &file_api_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryProto) ProtoMessage() {}

func (x *CategoryProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryProto.ProtoReflect.Descriptor instead.
func (*CategoryProto) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryProto) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CategoryProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryProto) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategoryProto) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CategoryProto) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CategoryProto) GetChildren() []*CategoryProto {
	if x != nil {
		return x.Children
	}
	return nil
}

type BrandProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandProto) Reset() {
	*x = BrandProto{}
	mi := &file_api_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandProto) ProtoMessage() {}

func (x *BrandProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandProto.ProtoReflect.Descriptor instead.
func (*BrandProto) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *BrandProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandProto) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *BrandProto) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *BrandProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SPUProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId        int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId           int64                  `protobuf:"varint,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Title             string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle          string                 `protobuf:"bytes,5,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Status            int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	SaleableAttrNames []string               `protobuf:"bytes,7,rep,name=saleable_attr_names,json=saleableAttrNames,proto3" json:"saleable_attr_names,omitempty"`
	SaleCount         int32                  `protobuf:"varint,8,opt,name=sale_count,json=saleCount,proto3" json:"sale_count,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Skus              []*SKUProto            `protobuf:"bytes,11,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SPUProto) Reset() {
	*x = SPUProto{}
	mi := &file_api_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPUProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPUProto) ProtoMessage() {}

func (x *SPUProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPUProto.ProtoReflect.Descriptor instead.
func (*SPUProto) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *SPUProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SPUProto) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SPUProto) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *SPUProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SPUProto) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *SPUProto) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SPUProto) GetSaleableAttrNames() []string {
	if x != nil {
		return x.SaleableAttrNames
	}
	return nil
}

func (x *SPUProto) GetSaleCount() int32 {
	if x != nil {
		return x.SaleCount
	}
	return 0
}

func (x *SPUProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SPUProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SPUProto) GetSkus() []*SKUProto {
	if x != nil {
		return x.Skus
	}
	return nil
}

type SKUProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpuId         int64                  `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,3,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	OriginPrice   float64                `protobuf:"fixed64,5,opt,name=origin_price,json=originPrice,proto3" json:"origin_price,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	LockedStock   int32                  `protobuf:"varint,7,opt,name=locked_stock,json=lockedStock,proto3" json:"locked_stock,omitempty"`
	Code          string                 `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	Image         string                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	SaleCount     int32                  `protobuf:"varint,11,opt,name=sale_count,json=saleCount,proto3" json:"sale_count,omitempty"`
	Version       int32                  `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKUProto) Reset() {
	*x = SKUProto{}
	mi := &file_api_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKUProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKUProto) ProtoMessage() {}

func (x *SKUProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKUProto.ProtoReflect.Descriptor instead.
func (*SKUProto) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *SKUProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SKUProto) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *SKUProto) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *SKUProto) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SKUProto) GetOriginPrice() float64 {
	if x != nil {
		return x.OriginPrice
	}
	return 0
}

func (x *SKUProto) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SKUProto) GetLockedStock() int32 {
	if x != nil {
		return x.LockedStock
	}
	return 0
}

func (x *SKUProto) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SKUProto) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SKUProto) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SKUProto) GetSaleCount() int32 {
	if x != nil {
		return x.SaleCount
	}
	return 0
}

func (x *SKUProto) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SKUProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SKUProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      int64                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCategoryRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateCategoryRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateCategoryRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCategoryTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryTreeRequest) Reset() {
	*x = GetCategoryTreeRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTreeRequest) ProtoMessage() {}

func (x *GetCategoryTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTreeRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryTreeRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{8}
}

type GetCategoryTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryProto       `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryTreeResponse) Reset() {
	*x = GetCategoryTreeResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTreeResponse) ProtoMessage() {}

func (x *GetCategoryTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTreeResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryTreeResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{9}
}

func (x *GetCategoryTreeResponse) GetCategories() []*CategoryProto {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *CategoryProto         `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{10}
}

func (x *CategoryResponse) GetCategory() *CategoryProto {
	if x != nil {
		return x.Category
	}
	return nil
}

type CreateBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBrandRequest) Reset() {
	*x = CreateBrandRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBrandRequest) ProtoMessage() {}

func (x *CreateBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBrandRequest.ProtoReflect.Descriptor instead.
func (*CreateBrandRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBrandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBrandRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *CreateBrandRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ListBrandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBrandsRequest) Reset() {
	*x = ListBrandsRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandsRequest) ProtoMessage() {}

func (x *ListBrandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandsRequest.ProtoReflect.Descriptor instead.
func (*ListBrandsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{12}
}

func (x *ListBrandsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListBrandsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBrandsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBrandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brands        []*BrandProto          `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBrandsResponse) Reset() {
	*x = ListBrandsResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandsResponse) ProtoMessage() {}

func (x *ListBrandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandsResponse.ProtoReflect.Descriptor instead.
func (*ListBrandsResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{13}
}

func (x *ListBrandsResponse) GetBrands() []*BrandProto {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *ListBrandsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         *BrandProto            `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandResponse) Reset() {
	*x = BrandResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandResponse) ProtoMessage() {}

func (x *BrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandResponse.ProtoReflect.Descriptor instead.
func (*BrandResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{14}
}

func (x *BrandResponse) GetBrand() *BrandProto {
	if x != nil {
		return x.Brand
	}
	return nil
}

type CreateSPURequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CategoryId        int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId           int64                  `protobuf:"varint,2,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle          string                 `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	SaleableAttrNames []string               `protobuf:"bytes,5,rep,name=saleable_attr_names,json=saleableAttrNames,proto3" json:"saleable_attr_names,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSPURequest) Reset() {
	*x = CreateSPURequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSPURequest) ProtoMessage() {}

func (x *CreateSPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSPURequest.ProtoReflect.Descriptor instead.
func (*CreateSPURequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{15}
}

func (x *CreateSPURequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateSPURequest) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *CreateSPURequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSPURequest) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *CreateSPURequest) GetSaleableAttrNames() []string {
	if x != nil {
		return x.SaleableAttrNames
	}
	return nil
}

type UpdateSPURequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId        int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId           int64                  `protobuf:"varint,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Title             string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle          string                 `protobuf:"bytes,5,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Status            int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	SaleableAttrNames []string               `protobuf:"bytes,7,rep,name=saleable_attr_names,json=saleableAttrNames,proto3" json:"saleable_attr_names,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateSPURequest) Reset() {
	*x = UpdateSPURequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSPURequest) ProtoMessage() {}

func (x *UpdateSPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSPURequest.ProtoReflect.Descriptor instead.
func (*UpdateSPURequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateSPURequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSPURequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateSPURequest) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *UpdateSPURequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSPURequest) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *UpdateSPURequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateSPURequest) GetSaleableAttrNames() []string {
	if x != nil {
		return x.SaleableAttrNames
	}
	return nil
}

type GetSPURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSPURequest) Reset() {
	*x = GetSPURequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSPURequest) ProtoMessage() {}

func (x *GetSPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSPURequest.ProtoReflect.Descriptor instead.
func (*GetSPURequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{17}
}

func (x *GetSPURequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListSPUsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId       int64                  `protobuf:"varint,2,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSPUsRequest) Reset() {
	*x = ListSPUsRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSPUsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSPUsRequest) ProtoMessage() {}

func (x *ListSPUsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSPUsRequest.ProtoReflect.Descriptor instead.
func (*ListSPUsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{18}
}

func (x *ListSPUsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListSPUsRequest) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *ListSPUsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListSPUsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListSPUsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSPUsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSPUsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spus          []*SPUProto            `protobuf:"bytes,1,rep,name=spus,proto3" json:"spus,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSPUsResponse) Reset() {
	*x = ListSPUsResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSPUsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSPUsResponse) ProtoMessage() {}

func (x *ListSPUsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSPUsResponse.ProtoReflect.Descriptor instead.
func (*ListSPUsResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{19}
}

func (x *ListSPUsResponse) GetSpus() []*SPUProto {
	if x != nil {
		return x.Spus
	}
	return nil
}

func (x *ListSPUsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SPUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spu           *SPUProto              `protobuf:"bytes,1,opt,name=spu,proto3" json:"spu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SPUResponse) Reset() {
	*x = SPUResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPUResponse) ProtoMessage() {}

func (x *SPUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPUResponse.ProtoReflect.Descriptor instead.
func (*SPUResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{20}
}

func (x *SPUResponse) GetSpu() *SPUProto {
	if x != nil {
		return x.Spu
	}
	return nil
}

type BatchCreateSKURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         int64                  `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Skus          []*CreateSKUItem       `protobuf:"bytes,2,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateSKURequest) Reset() {
	*x = BatchCreateSKURequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateSKURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateSKURequest) ProtoMessage() {}

func (x *BatchCreateSKURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateSKURequest.ProtoReflect.Descriptor instead.
func (*BatchCreateSKURequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{21}
}

func (x *BatchCreateSKURequest) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *BatchCreateSKURequest) GetSkus() []*CreateSKUItem {
	if x != nil {
		return x.Skus
	}
	return nil
}

type CreateSKUItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attrs         map[string]string      `protobuf:"bytes,1,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	OriginPrice   float64                `protobuf:"fixed64,3,opt,name=origin_price,json=originPrice,proto3" json:"origin_price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSKUItem) Reset() {
	*x = CreateSKUItem{}
	mi := &file_api_product_v1_product_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSKUItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSKUItem) ProtoMessage() {}

func (x *CreateSKUItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSKUItem.ProtoReflect.Descriptor instead.
func (*CreateSKUItem) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{22}
}

func (x *CreateSKUItem) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *CreateSKUItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSKUItem) GetOriginPrice() float64 {
	if x != nil {
		return x.OriginPrice
	}
	return 0
}

func (x *CreateSKUItem) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateSKUItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateSKUItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type BatchCreateSKUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []*SKUProto            `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateSKUResponse) Reset() {
	*x = BatchCreateSKUResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateSKUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateSKUResponse) ProtoMessage() {}

func (x *BatchCreateSKUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateSKUResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateSKUResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{23}
}

func (x *BatchCreateSKUResponse) GetSkus() []*SKUProto {
	if x != nil {
		return x.Skus
	}
	return nil
}

type UpdateSKURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	OriginPrice   float64                `protobuf:"fixed64,3,opt,name=origin_price,json=originPrice,proto3" json:"origin_price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSKURequest) Reset() {
	*x = UpdateSKURequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSKURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSKURequest) ProtoMessage() {}

func (x *UpdateSKURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSKURequest.ProtoReflect.Descriptor instead.
func (*UpdateSKURequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateSKURequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSKURequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateSKURequest) GetOriginPrice() float64 {
	if x != nil {
		return x.OriginPrice
	}
	return 0
}

func (x *UpdateSKURequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateSKURequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateSKURequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateSKURequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListSKUsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         int64                  `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSKUsRequest) Reset() {
	*x = ListSKUsRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSKUsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSKUsRequest) ProtoMessage() {}

func (x *ListSKUsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSKUsRequest.ProtoReflect.Descriptor instead.
func (*ListSKUsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{25}
}

func (x *ListSKUsRequest) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

type ListSKUsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []*SKUProto            `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSKUsResponse) Reset() {
	*x = ListSKUsResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSKUsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSKUsResponse) ProtoMessage() {}

func (x *ListSKUsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSKUsResponse.ProtoReflect.Descriptor instead.
func (*ListSKUsResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{26}
}

func (x *ListSKUsResponse) GetSkus() []*SKUProto {
	if x != nil {
		return x.Skus
	}
	return nil
}

type SKUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *SKUProto              `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKUResponse) Reset() {
	*x = SKUResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKUResponse) ProtoMessage() {}

func (x *SKUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKUResponse.ProtoReflect.Descriptor instead.
func (*SKUResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{27}
}

func (x *SKUResponse) GetSku() *SKUProto {
	if x != nil {
		return x.Sku
	}
	return nil
}

type LockStockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStockItem) Reset() {
	*x = LockStockItem{}
	mi := &file_api_product_v1_product_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStockItem) ProtoMessage() {}

func (x *LockStockItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStockItem.ProtoReflect.Descriptor instead.
func (*LockStockItem) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{28}
}

func (x *LockStockItem) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *LockStockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *LockStockItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type LockStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Items         []*LockStockItem       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStockRequest) Reset() {
	*x = LockStockRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStockRequest) ProtoMessage() {}

func (x *LockStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStockRequest.ProtoReflect.Descriptor instead.
func (*LockStockRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{29}
}

func (x *LockStockRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *LockStockRequest) GetItems() []*LockStockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type LockStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStockResponse) Reset() {
	*x = LockStockResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStockResponse) ProtoMessage() {}

func (x *LockStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStockResponse.ProtoReflect.Descriptor instead.
func (*LockStockResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{30}
}

func (x *LockStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConfirmDeductItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDeductItem) Reset() {
	*x = ConfirmDeductItem{}
	mi := &file_api_product_v1_product_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeductItem) ProtoMessage() {}

func (x *ConfirmDeductItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDeductItem.ProtoReflect.Descriptor instead.
func (*ConfirmDeductItem) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{31}
}

func (x *ConfirmDeductItem) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *ConfirmDeductItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ConfirmDeductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Items         []*ConfirmDeductItem   `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDeductRequest) Reset() {
	*x = ConfirmDeductRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeductRequest) ProtoMessage() {}

func (x *ConfirmDeductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDeductRequest.ProtoReflect.Descriptor instead.
func (*ConfirmDeductRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{32}
}

func (x *ConfirmDeductRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ConfirmDeductRequest) GetItems() []*ConfirmDeductItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UnlockStockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockStockItem) Reset() {
	*x = UnlockStockItem{}
	mi := &file_api_product_v1_product_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockStockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockStockItem) ProtoMessage() {}

func (x *UnlockStockItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockStockItem.ProtoReflect.Descriptor instead.
func (*UnlockStockItem) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{33}
}

func (x *UnlockStockItem) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *UnlockStockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UnlockStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Items         []*UnlockStockItem     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockStockRequest) Reset() {
	*x = UnlockStockRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockStockRequest) ProtoMessage() {}

func (x *UnlockStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockStockRequest.ProtoReflect.Descriptor instead.
func (*UnlockStockRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{34}
}

func (x *UnlockStockRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *UnlockStockRequest) GetItems() []*UnlockStockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_product_v1_product_proto protoreflect.FileDescriptor

const file_api_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x1capi/product/v1/product.proto\x12\n" +
	"product.v1\"\a\n" +
	"\x05Empty\"\xef\x01\n" +
	"\rCategoryProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x125\n" +
	"\bchildren\x18\b \x03(\v2\x19.product.v1.CategoryProtoR\bchildren\"\x82\x01\n" +
	"\n" +
	"BrandProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xd7\x02\n" +
	"\bSPUProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x03 \x01(\x03R\abrandId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x05 \x01(\tR\bsubtitle\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12.\n" +
	"\x13saleable_attr_names\x18\a \x03(\tR\x11saleableAttrNames\x12\x1d\n" +
	"\n" +
	"sale_count\x18\b \x01(\x05R\tsaleCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12(\n" +
	"\x04skus\x18\v \x03(\v2\x14.product.v1.SKUProtoR\x04skus\"\xcd\x03\n" +
	"\bSKUProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06spu_id\x18\x02 \x01(\x03R\x05spuId\x125\n" +
	"\x05attrs\x18\x03 \x03(\v2\x1f.product.v1.SKUProto.AttrsEntryR\x05attrs\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12!\n" +
	"\forigin_price\x18\x05 \x01(\x01R\voriginPrice\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12!\n" +
	"\flocked_stock\x18\a \x01(\x05R\vlockedStock\x12\x12\n" +
	"\x04code\x18\b \x01(\tR\x04code\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"sale_count\x18\v \x01(\x05R\tsaleCount\x12\x18\n" +
	"\aversion\x18\f \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x15CreateCategoryRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"n\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x18\n" +
	"\x16GetCategoryTreeRequest\"T\n" +
	"\x17GetCategoryTreeResponse\x129\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x19.product.v1.CategoryProtoR\n" +
	"categories\"I\n" +
	"\x10CategoryResponse\x125\n" +
	"\bcategory\x18\x01 \x01(\v2\x19.product.v1.CategoryProtoR\bcategory\"[\n" +
	"\x12CreateBrandRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x02 \x01(\tR\x04logo\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"^\n" +
	"\x11ListBrandsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"Z\n" +
	"\x12ListBrandsResponse\x12.\n" +
	"\x06brands\x18\x01 \x03(\v2\x16.product.v1.BrandProtoR\x06brands\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"=\n" +
	"\rBrandResponse\x12,\n" +
	"\x05brand\x18\x01 \x01(\v2\x16.product.v1.BrandProtoR\x05brand\"\xb0\x01\n" +
	"\x10CreateSPURequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x02 \x01(\x03R\abrandId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x04 \x01(\tR\bsubtitle\x12.\n" +
	"\x13saleable_attr_names\x18\x05 \x03(\tR\x11saleableAttrNames\"\xd8\x01\n" +
	"\x10UpdateSPURequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x03 \x01(\x03R\abrandId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x05 \x01(\tR\bsubtitle\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12.\n" +
	"\x13saleable_attr_names\x18\a \x03(\tR\x11saleableAttrNames\"\x1f\n" +
	"\rGetSPURequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb0\x01\n" +
	"\x0fListSPUsRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x02 \x01(\x03R\abrandId\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"R\n" +
	"\x10ListSPUsResponse\x12(\n" +
	"\x04spus\x18\x01 \x03(\v2\x14.product.v1.SPUProtoR\x04spus\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"5\n" +
	"\vSPUResponse\x12&\n" +
	"\x03spu\x18\x01 \x01(\v2\x14.product.v1.SPUProtoR\x03spu\"]\n" +
	"\x15BatchCreateSKURequest\x12\x15\n" +
	"\x06spu_id\x18\x01 \x01(\x03R\x05spuId\x12-\n" +
	"\x04skus\x18\x02 \x03(\v2\x19.product.v1.CreateSKUItemR\x04skus\"\xfe\x01\n" +
	"\rCreateSKUItem\x12:\n" +
	"\x05attrs\x18\x01 \x03(\v2$.product.v1.CreateSKUItem.AttrsEntryR\x05attrs\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12!\n" +
	"\forigin_price\x18\x03 \x01(\x01R\voriginPrice\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x16BatchCreateSKUResponse\x12(\n" +
	"\x04skus\x18\x01 \x03(\v2\x14.product.v1.SKUProtoR\x04skus\"\xb3\x01\n" +
	"\x10UpdateSKURequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12!\n" +
	"\forigin_price\x18\x03 \x01(\x01R\voriginPrice\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"(\n" +
	"\x0fListSKUsRequest\x12\x15\n" +
	"\x06spu_id\x18\x01 \x01(\x03R\x05spuId\"<\n" +
	"\x10ListSKUsResponse\x12(\n" +
	"\x04skus\x18\x01 \x03(\v2\x14.product.v1.SKUProtoR\x04skus\"5\n" +
	"\vSKUResponse\x12&\n" +
	"\x03sku\x18\x01 \x01(\v2\x14.product.v1.SKUProtoR\x03sku\"\\\n" +
	"\rLockStockItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\"^\n" +
	"\x10LockStockRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.product.v1.LockStockItemR\x05items\"-\n" +
	"\x11LockStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x11ConfirmDeductItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"f\n" +
	"\x14ConfirmDeductRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x123\n" +
	"\x05items\x18\x02 \x03(\v2\x1d.product.v1.ConfirmDeductItemR\x05items\"D\n" +
	"\x0fUnlockStockItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"b\n" +
	"\x12UnlockStockRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.product.v1.UnlockStockItemR\x05items*\x88\x02\n" +
	"\x12ProductErrorReason\x12\x16\n" +
	"\x12CATEGORY_NOT_FOUND\x10\x00\x12\x19\n" +
	"\x15CATEGORY_HAS_CHILDREN\x10\x01\x12\x13\n" +
	"\x0fBRAND_NOT_FOUND\x10\x02\x12\x11\n" +
	"\rSPU_NOT_FOUND\x10\x03\x12\x11\n" +
	"\rSKU_NOT_FOUND\x10\x04\x12\x16\n" +
	"\x12STOCK_INSUFFICIENT\x10\x05\x12\x17\n" +
	"\x13STOCK_LOCK_CONFLICT\x10\x06\x12\x1e\n" +
	"\x1aSTOCK_OPERATION_DUPLICATED\x10\a\x12\x14\n" +
	"\x10SKU_ATTR_INVALID\x10\b\x12\x1d\n" +
	"\x19STATUS_TRANSITION_INVALID\x10\t2\xb9\t\n" +
	"\x0eProductService\x12Q\n" +
	"\x0eCreateCategory\x12!.product.v1.CreateCategoryRequest\x1a\x1c.product.v1.CategoryResponse\x12Q\n" +
	"\x0eUpdateCategory\x12!.product.v1.UpdateCategoryRequest\x1a\x1c.product.v1.CategoryResponse\x12F\n" +
	"\x0eDeleteCategory\x12!.product.v1.DeleteCategoryRequest\x1a\x11.product.v1.Empty\x12Z\n" +
	"\x0fGetCategoryTree\x12\".product.v1.GetCategoryTreeRequest\x1a#.product.v1.GetCategoryTreeResponse\x12H\n" +
	"\vCreateBrand\x12\x1e.product.v1.CreateBrandRequest\x1a\x19.product.v1.BrandResponse\x12K\n" +
	"\n" +
	"ListBrands\x12\x1d.product.v1.ListBrandsRequest\x1a\x1e.product.v1.ListBrandsResponse\x12B\n" +
	"\tCreateSPU\x12\x1c.product.v1.CreateSPURequest\x1a\x17.product.v1.SPUResponse\x12B\n" +
	"\tUpdateSPU\x12\x1c.product.v1.UpdateSPURequest\x1a\x17.product.v1.SPUResponse\x12<\n" +
	"\x06GetSPU\x12\x19.product.v1.GetSPURequest\x1a\x17.product.v1.SPUResponse\x12E\n" +
	"\bListSPUs\x12\x1b.product.v1.ListSPUsRequest\x1a\x1c.product.v1.ListSPUsResponse\x12W\n" +
	"\x0eBatchCreateSKU\x12!.product.v1.BatchCreateSKURequest\x1a\".product.v1.BatchCreateSKUResponse\x12B\n" +
	"\tUpdateSKU\x12\x1c.product.v1.UpdateSKURequest\x1a\x17.product.v1.SKUResponse\x12E\n" +
	"\bListSKUs\x12\x1b.product.v1.ListSKUsRequest\x1a\x1c.product.v1.ListSKUsResponse\x12H\n" +
	"\tLockStock\x12\x1c.product.v1.LockStockRequest\x1a\x1d.product.v1.LockStockResponse\x12I\n" +
	"\x12ConfirmDeductStock\x12 .product.v1.ConfirmDeductRequest\x1a\x11.product.v1.Empty\x12@\n" +
	"\vUnlockStock\x12\x1e.product.v1.UnlockStockRequest\x1a\x11.product.v1.EmptyB+Z)github.com/storm/myidea/api/product/v1;v1b\x06proto3"

var (
	file_api_product_v1_product_proto_rawDescOnce sync.Once
	file_api_product_v1_product_proto_rawDescData []byte
)

func file_api_product_v1_product_proto_rawDescGZIP() []byte {
	file_api_product_v1_product_proto_rawDescOnce.Do(func() {
		file_api_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_product_v1_product_proto_rawDesc), len(file_api_product_v1_product_proto_rawDesc)))
	})
	return file_api_product_v1_product_proto_rawDescData
}

var file_api_product_v1_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_api_product_v1_product_proto_goTypes = []any{
	(ProductErrorReason)(0),         // 0: product.v1.ProductErrorReason
	(*Empty)(nil),                   // 1: product.v1.Empty
	(*CategoryProto)(nil),           // 2: product.v1.CategoryProto
	(*BrandProto)(nil),              // 3: product.v1.BrandProto
	(*SPUProto)(nil),                // 4: product.v1.SPUProto
	(*SKUProto)(nil),                // 5: product.v1.SKUProto
	(*CreateCategoryRequest)(nil),   // 6: product.v1.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),   // 7: product.v1.UpdateCategoryRequest
	(*DeleteCategoryRequest)(nil),   // 8: product.v1.DeleteCategoryRequest
	(*GetCategoryTreeRequest)(nil),  // 9: product.v1.GetCategoryTreeRequest
	(*GetCategoryTreeResponse)(nil), // 10: product.v1.GetCategoryTreeResponse
	(*CategoryResponse)(nil),        // 11: product.v1.CategoryResponse
	(*CreateBrandRequest)(nil),      // 12: product.v1.CreateBrandRequest
	(*ListBrandsRequest)(nil),       // 13: product.v1.ListBrandsRequest
	(*ListBrandsResponse)(nil),      // 14: product.v1.ListBrandsResponse
	(*BrandResponse)(nil),           // 15: product.v1.BrandResponse
	(*CreateSPURequest)(nil),        // 16: product.v1.CreateSPURequest
	(*UpdateSPURequest)(nil),        // 17: product.v1.UpdateSPURequest
	(*GetSPURequest)(nil),           // 18: product.v1.GetSPURequest
	(*ListSPUsRequest)(nil),         // 19: product.v1.ListSPUsRequest
	(*ListSPUsResponse)(nil),        // 20: product.v1.ListSPUsResponse
	(*SPUResponse)(nil),             // 21: product.v1.SPUResponse
	(*BatchCreateSKURequest)(nil),   // 22: product.v1.BatchCreateSKURequest
	(*CreateSKUItem)(nil),           // 23: product.v1.CreateSKUItem
	(*BatchCreateSKUResponse)(nil),  // 24: product.v1.BatchCreateSKUResponse
	(*UpdateSKURequest)(nil),        // 25: product.v1.UpdateSKURequest
	(*ListSKUsRequest)(nil),         // 26: product.v1.ListSKUsRequest
	(*ListSKUsResponse)(nil),        // 27: product.v1.ListSKUsResponse
	(*SKUResponse)(nil),             // 28: product.v1.SKUResponse
	(*LockStockItem)(nil),           // 29: product.v1.LockStockItem
	(*LockStockRequest)(nil),        // 30: product.v1.LockStockRequest
	(*LockStockResponse)(nil),       // 31: product.v1.LockStockResponse
	(*ConfirmDeductItem)(nil),       // 32: product.v1.ConfirmDeductItem
	(*ConfirmDeductRequest)(nil),    // 33: product.v1.ConfirmDeductRequest
	(*UnlockStockItem)(nil),         // 34: product.v1.UnlockStockItem
	(*UnlockStockRequest)(nil),      // 35: product.v1.UnlockStockRequest
	nil,                             // 36: product.v1.SKUProto.AttrsEntry
	nil,                             // 37: product.v1.CreateSKUItem.AttrsEntry
}
var file_api_product_v1_product_proto_depIdxs = []int32{
	2,  // 0: product.v1.CategoryProto.children:type_name -> product.v1.CategoryProto
	5,  // 1: product.v1.SPUProto.skus:type_name -> product.v1.SKUProto
	36, // 2: product.v1.SKUProto.attrs:type_name -> product.v1.SKUProto.AttrsEntry
	2,  // 3: product.v1.GetCategoryTreeResponse.categories:type_name -> product.v1.CategoryProto
	2,  // 4: product.v1.CategoryResponse.category:type_name -> product.v1.CategoryProto
	3,  // 5: product.v1.ListBrandsResponse.brands:type_name -> product.v1.BrandProto
	3,  // 6: product.v1.BrandResponse.brand:type_name -> product.v1.BrandProto
	4,  // 7: product.v1.ListSPUsResponse.spus:type_name -> product.v1.SPUProto
	4,  // 8: product.v1.SPUResponse.spu:type_name -> product.v1.SPUProto
	23, // 9: product.v1.BatchCreateSKURequest.skus:type_name -> product.v1.CreateSKUItem
	37, // 10: product.v1.CreateSKUItem.attrs:type_name -> product.v1.CreateSKUItem.AttrsEntry
	5,  // 11: product.v1.BatchCreateSKUResponse.skus:type_name -> product.v1.SKUProto
	5,  // 12: product.v1.ListSKUsResponse.skus:type_name -> product.v1.SKUProto
	5,  // 13: product.v1.SKUResponse.sku:type_name -> product.v1.SKUProto
	29, // 14: product.v1.LockStockRequest.items:type_name -> product.v1.LockStockItem
	32, // 15: product.v1.ConfirmDeductRequest.items:type_name -> product.v1.ConfirmDeductItem
	34, // 16: product.v1.UnlockStockRequest.items:type_name -> product.v1.UnlockStockItem
	6,  // 17: product.v1.ProductService.CreateCategory:input_type -> product.v1.CreateCategoryRequest
	7,  // 18: product.v1.ProductService.UpdateCategory:input_type -> product.v1.UpdateCategoryRequest
	8,  // 19: product.v1.ProductService.DeleteCategory:input_type -> product.v1.DeleteCategoryRequest
	9,  // 20: product.v1.ProductService.GetCategoryTree:input_type -> product.v1.GetCategoryTreeRequest
	12, // 21: product.v1.ProductService.CreateBrand:input_type -> product.v1.CreateBrandRequest
	13, // 22: product.v1.ProductService.ListBrands:input_type -> product.v1.ListBrandsRequest
	16, // 23: product.v1.ProductService.CreateSPU:input_type -> product.v1.CreateSPURequest
	17, // 24: product.v1.ProductService.UpdateSPU:input_type -> product.v1.UpdateSPURequest
	18, // 25: product.v1.ProductService.GetSPU:input_type -> product.v1.GetSPURequest
	19, // 26: product.v1.ProductService.ListSPUs:input_type -> product.v1.ListSPUsRequest
	22, // 27: product.v1.ProductService.BatchCreateSKU:input_type -> product.v1.BatchCreateSKURequest
	25, // 28: product.v1.ProductService.UpdateSKU:input_type -> product.v1.UpdateSKURequest
	26, // 29: product.v1.ProductService.ListSKUs:input_type -> product.v1.ListSKUsRequest
	30, // 30: product.v1.ProductService.LockStock:input_type -> product.v1.LockStockRequest
	33, // 31: product.v1.ProductService.ConfirmDeductStock:input_type -> product.v1.ConfirmDeductRequest
	35, // 32: product.v1.ProductService.UnlockStock:input_type -> product.v1.UnlockStockRequest
	11, // 33: product.v1.ProductService.CreateCategory:output_type -> product.v1.CategoryResponse
	11, // 34: product.v1.ProductService.UpdateCategory:output_type -> product.v1.CategoryResponse
	1,  // 35: product.v1.ProductService.DeleteCategory:output_type -> product.v1.Empty
	10, // 36: product.v1.ProductService.GetCategoryTree:output_type -> product.v1.GetCategoryTreeResponse
	15, // 37: product.v1.ProductService.CreateBrand:output_type -> product.v1.BrandResponse
	14, // 38: product.v1.ProductService.ListBrands:output_type -> product.v1.ListBrandsResponse
	21, // 39: product.v1.ProductService.CreateSPU:output_type -> product.v1.SPUResponse
	21, // 40: product.v1.ProductService.UpdateSPU:output_type -> product.v1.SPUResponse
	21, // 41: product.v1.ProductService.GetSPU:output_type -> product.v1.SPUResponse
	20, // 42: product.v1.ProductService.ListSPUs:output_type -> product.v1.ListSPUsResponse
	24, // 43: product.v1.ProductService.BatchCreateSKU:output_type -> product.v1.BatchCreateSKUResponse
	28, // 44: product.v1.ProductService.UpdateSKU:output_type -> product.v1.SKUResponse
	27, // 45: product.v1.ProductService.ListSKUs:output_type -> product.v1.ListSKUsResponse
	31, // 46: product.v1.ProductService.LockStock:output_type -> product.v1.LockStockResponse
	1,  // 47: product.v1.ProductService.ConfirmDeductStock:output_type -> product.v1.Empty
	1,  // 48: product.v1.ProductService.UnlockStock:output_type -> product.v1.Empty
	33, // [33:49] is the sub-list for method output_type
	17, // [17:33] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_product_v1_product_proto_init() }
func file_api_product_v1_product_proto_init() {
	if File_api_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_product_v1_product_proto_rawDesc), len(file_api_product_v1_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_product_v1_product_proto_goTypes,
		DependencyIndexes: file_api_product_v1_product_proto_depIdxs,
		EnumInfos:         file_api_product_v1_product_proto_enumTypes,
		MessageInfos:      file_api_product_v1_product_proto_msgTypes,
	}.Build()
	File_api_product_v1_product_proto = out.File
	file_api_product_v1_product_proto_goTypes = nil
	file_api_product_v1_product_proto_depIdxs = nil
}
