// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/cart/v1/cart.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CartErrorReason defines business error codes for the cart domain.
type CartErrorReason int32

const (
	CartErrorReason_CART_ITEM_NOT_FOUND   CartErrorReason = 0
	CartErrorReason_CART_QUANTITY_INVALID CartErrorReason = 1
	CartErrorReason_CART_ITEM_DUPLICATED  CartErrorReason = 2
)

// Enum value maps for CartErrorReason.
var (
	CartErrorReason_name = map[int32]string{
		0: "CART_ITEM_NOT_FOUND",
		1: "CART_QUANTITY_INVALID",
		2: "CART_ITEM_DUPLICATED",
	}
	CartErrorReason_value = map[string]int32{
		"CART_ITEM_NOT_FOUND":   0,
		"CART_QUANTITY_INVALID": 1,
		"CART_ITEM_DUPLICATED":  2,
	}
)

func (x CartErrorReason) Enum() *CartErrorReason {
	p := new(CartErrorReason)
	*p = x
	return p
}

func (x CartErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CartErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_cart_v1_cart_proto_enumTypes[0].Descriptor()
}

func (CartErrorReason) Type() protoreflect.EnumType {
	return &file_api_cart_v1_cart_proto_enumTypes[0]
}

func (x CartErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CartErrorReason.Descriptor instead.
func (CartErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

type CartItemProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,4,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId         int64                  `protobuf:"varint,5,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	ShopId        int64                  `protobuf:"varint,6,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Image         string                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,9,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Price         float64                `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,11,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Selected      bool                   `protobuf:"varint,12,opt,name=selected,proto3" json:"selected,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemProto) Reset() {
	*x = CartItemProto{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemProto) ProtoMessage() {}

func (x *CartItemProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemProto.ProtoReflect.Descriptor instead.
func (*CartItemProto) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartItemProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItemProto) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItemProto) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItemProto) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItemProto) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *CartItemProto) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *CartItemProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CartItemProto) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CartItemProto) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *CartItemProto) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItemProto) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItemProto) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *CartItemProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CartItemProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,3,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId         int64                  `protobuf:"varint,4,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	ShopId        int64                  `protobuf:"varint,5,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,8,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Price         float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,10,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *AddItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddItemRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *AddItemRequest) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *AddItemRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *AddItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddItemRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AddItemRequest) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *AddItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuantityRequest) Reset() {
	*x = UpdateQuantityRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuantityRequest) ProtoMessage() {}

func (x *UpdateQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuantityRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateQuantityRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateQuantityRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UpdateQuantityRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveItemRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *ListItemsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItemProto       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{6}
}

func (x *ListItemsResponse) GetItems() []*CartItemProto {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClearItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemIds       []int64                `protobuf:"varint,2,rep,packed,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearItemsRequest) Reset() {
	*x = ClearItemsRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearItemsRequest) ProtoMessage() {}

func (x *ClearItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearItemsRequest.ProtoReflect.Descriptor instead.
func (*ClearItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{7}
}

func (x *ClearItemsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClearItemsRequest) GetItemIds() []int64 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

var File_api_cart_v1_cart_proto protoreflect.FileDescriptor

const file_api_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x16api/cart/v1/cart.proto\x12\acart.v1\"\a\n" +
	"\x05Empty\"\xc9\x03\n" +
	"\rCartItemProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x15\n" +
	"\x06sku_id\x18\x04 \x01(\x03R\x05skuId\x12\x15\n" +
	"\x06spu_id\x18\x05 \x01(\x03R\x05spuId\x12\x17\n" +
	"\ashop_id\x18\x06 \x01(\x03R\x06shopId\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\x127\n" +
	"\x05attrs\x18\t \x03(\v2!.cart.v1.CartItemProto.AttrsEntryR\x05attrs\x12\x14\n" +
	"\x05price\x18\n" +
	" \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\v \x01(\x05R\bquantity\x12\x1a\n" +
	"\bselected\x18\f \x01(\bR\bselected\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x02\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x15\n" +
	"\x06sku_id\x18\x03 \x01(\x03R\x05skuId\x12\x15\n" +
	"\x06spu_id\x18\x04 \x01(\x03R\x05spuId\x12\x17\n" +
	"\ashop_id\x18\x05 \x01(\x03R\x06shopId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x128\n" +
	"\x05attrs\x18\b \x03(\v2\".cart.v1.AddItemRequest.AttrsEntryR\x05attrs\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\n" +
	" \x01(\x05R\bquantity\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x15UpdateQuantityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"E\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\"+\n" +
	"\x10ListItemsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"A\n" +
	"\x11ListItemsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.cart.v1.CartItemProtoR\x05items\"G\n" +
	"\x11ClearItemsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bitem_ids\x18\x02 \x03(\x03R\aitemIds*_\n" +
	"\x0fCartErrorReason\x12\x17\n" +
	"\x13CART_ITEM_NOT_FOUND\x10\x00\x12\x19\n" +
	"\x15CART_QUANTITY_INVALID\x10\x01\x12\x18\n" +
	"\x14CART_ITEM_DUPLICATED\x10\x022\xcb\x02\n" +
	"\vCartService\x12:\n" +
	"\aAddItem\x12\x17.cart.v1.AddItemRequest\x1a\x16.cart.v1.CartItemProto\x12H\n" +
	"\x0eUpdateQuantity\x12\x1e.cart.v1.UpdateQuantityRequest\x1a\x16.cart.v1.CartItemProto\x128\n" +
	"\n" +
	"RemoveItem\x12\x1a.cart.v1.RemoveItemRequest\x1a\x0e.cart.v1.Empty\x12B\n" +
	"\tListItems\x12\x19.cart.v1.ListItemsRequest\x1a\x1a.cart.v1.ListItemsResponse\x128\n" +
	"\n" +
	"ClearItems\x12\x1a.cart.v1.ClearItemsRequest\x1a\x0e.cart.v1.EmptyB(Z&github.com/storm/myidea/api/cart/v1;v1b\x06proto3"

var (
	file_api_cart_v1_cart_proto_rawDescOnce sync.Once
	file_api_cart_v1_cart_proto_rawDescData []byte
)

func file_api_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_api_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_api_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cart_v1_cart_proto_rawDesc), len(file_api_cart_v1_cart_proto_rawDesc)))
	})
	return file_api_cart_v1_cart_proto_rawDescData
}

var file_api_cart_v1_cart_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_cart_v1_cart_proto_goTypes = []any{
	(CartErrorReason)(0),          // 0: cart.v1.CartErrorReason
	(*Empty)(nil),                 // 1: cart.v1.Empty
	(*CartItemProto)(nil),         // 2: cart.v1.CartItemProto
	(*AddItemRequest)(nil),        // 3: cart.v1.AddItemRequest
	(*UpdateQuantityRequest)(nil), // 4: cart.v1.UpdateQuantityRequest
	(*RemoveItemRequest)(nil),     // 5: cart.v1.RemoveItemRequest
	(*ListItemsRequest)(nil),      // 6: cart.v1.ListItemsRequest
	(*ListItemsResponse)(nil),     // 7: cart.v1.ListItemsResponse
	(*ClearItemsRequest)(nil),     // 8: cart.v1.ClearItemsRequest
	nil,                           // 9: cart.v1.CartItemProto.AttrsEntry
	nil,                           // 10: cart.v1.AddItemRequest.AttrsEntry
}
var file_api_cart_v1_cart_proto_depIdxs = []int32{
	9,  // 0: cart.v1.CartItemProto.attrs:type_name -> cart.v1.CartItemProto.AttrsEntry
	10, // 1: cart.v1.AddItemRequest.attrs:type_name -> cart.v1.AddItemRequest.AttrsEntry
	2,  // 2: cart.v1.ListItemsResponse.items:type_name -> cart.v1.CartItemProto
	3,  // 3: cart.v1.CartService.AddItem:input_type -> cart.v1.AddItemRequest
	4,  // 4: cart.v1.CartService.UpdateQuantity:input_type -> cart.v1.UpdateQuantityRequest
	5,  // 5: cart.v1.CartService.RemoveItem:input_type -> cart.v1.RemoveItemRequest
	6,  // 6: cart.v1.CartService.ListItems:input_type -> cart.v1.ListItemsRequest
	8,  // 7: cart.v1.CartService.ClearItems:input_type -> cart.v1.ClearItemsRequest
	2,  // 8: cart.v1.CartService.AddItem:output_type -> cart.v1.CartItemProto
	2,  // 9: cart.v1.CartService.UpdateQuantity:output_type -> cart.v1.CartItemProto
	1,  // 10: cart.v1.CartService.RemoveItem:output_type -> cart.v1.Empty
	7,  // 11: cart.v1.CartService.ListItems:output_type -> cart.v1.ListItemsResponse
	1,  // 12: cart.v1.CartService.ClearItems:output_type -> cart.v1.Empty
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_cart_v1_cart_proto_init() }
func file_api_cart_v1_cart_proto_init() {
	if File_api_cart_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cart_v1_cart_proto_rawDesc), len(file_api_cart_v1_cart_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_api_cart_v1_cart_proto_depIdxs,
		EnumInfos:         file_api_cart_v1_cart_proto_enumTypes,
		MessageInfos:      file_api_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_api_cart_v1_cart_proto = out.File
	file_api_cart_v1_cart_proto_goTypes = nil
	file_api_cart_v1_cart_proto_depIdxs = nil
}
