// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/payment/v1/payment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentStatus represents the lifecycle of a payment.
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PENDING                    PaymentStatus = 1 // Created but not yet processed
	PaymentStatus_SUCCESS                    PaymentStatus = 2 // Payment completed successfully
	PaymentStatus_FAILED                     PaymentStatus = 3 // Payment failed
	PaymentStatus_REFUNDING                  PaymentStatus = 4 // Refund in progress
	PaymentStatus_REFUNDED                   PaymentStatus = 5 // Fully refunded
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "SUCCESS",
		3: "FAILED",
		4: "REFUNDING",
		5: "REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PENDING":                    1,
		"SUCCESS":                    2,
		"FAILED":                     3,
		"REFUNDING":                  4,
		"REFUNDED":                   5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_api_payment_v1_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

// PaymentMethod represents the payment channel.
// MOCK is the built-in mock provider for development.
// ALIPAY / WECHAT_PAY are reserved for third-party SDK integration.
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_MOCK                       PaymentMethod = 1 // Built-in mock provider for dev/test
	PaymentMethod_ALIPAY                     PaymentMethod = 2 // Reserved for Alipay SDK
	PaymentMethod_WECHAT_PAY                 PaymentMethod = 3 // Reserved for WeChat Pay SDK
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "MOCK",
		2: "ALIPAY",
		3: "WECHAT_PAY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"MOCK":                       1,
		"ALIPAY":                     2,
		"WECHAT_PAY":                 3,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_payment_v1_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_api_payment_v1_payment_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

type PaymentProto struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId              int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo             string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	TotalAmount         float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaidAmount          float64                `protobuf:"fixed64,5,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	Status              PaymentStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=payment.v1.PaymentStatus" json:"status,omitempty"`
	Method              PaymentMethod          `protobuf:"varint,7,opt,name=method,proto3,enum=payment.v1.PaymentMethod" json:"method,omitempty"`
	ProviderTradeNo     string                 `protobuf:"bytes,8,opt,name=provider_trade_no,json=providerTradeNo,proto3" json:"provider_trade_no,omitempty"`             // Transaction ID from third-party provider (e.g. Alipay trade_no)
	ProviderRawResponse string                 `protobuf:"bytes,9,opt,name=provider_raw_response,json=providerRawResponse,proto3" json:"provider_raw_response,omitempty"` // Raw response from the provider SDK (for debugging/audit)
	FailReason          string                 `protobuf:"bytes,10,opt,name=fail_reason,json=failReason,proto3" json:"fail_reason,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PaymentProto) Reset() {
	*x = PaymentProto{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentProto) ProtoMessage() {}

func (x *PaymentProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentProto.ProtoReflect.Descriptor instead.
func (*PaymentProto) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentProto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentProto) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentProto) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PaymentProto) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *PaymentProto) GetPaidAmount() float64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *PaymentProto) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentProto) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *PaymentProto) GetProviderTradeNo() string {
	if x != nil {
		return x.ProviderTradeNo
	}
	return ""
}

func (x *PaymentProto) GetProviderRawResponse() string {
	if x != nil {
		return x.ProviderRawResponse
	}
	return ""
}

func (x *PaymentProto) GetFailReason() string {
	if x != nil {
		return x.FailReason
	}
	return ""
}

func (x *PaymentProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,4,opt,name=method,proto3,enum=payment.v1.PaymentMethod" json:"method,omitempty"` // Which payment channel to use (default: MOCK)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreatePaymentRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreatePaymentRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentProto          `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentResponse) GetPayment() *PaymentProto {
	if x != nil {
		return x.Payment
	}
	return nil
}

type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,2,opt,name=method,proto3,enum=payment.v1.PaymentMethod" json:"method,omitempty"` // Override the payment channel if needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessPaymentRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *ProcessPaymentRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentProto          `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessPaymentResponse) GetPayment() *PaymentProto {
	if x != nil {
		return x.Payment
	}
	return nil
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentProto          `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentResponse) GetPayment() *PaymentProto {
	if x != nil {
		return x.Payment
	}
	return nil
}

type GetPaymentByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByOrderRequest) Reset() {
	*x = GetPaymentByOrderRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByOrderRequest) ProtoMessage() {}

func (x *GetPaymentByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentByOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetPaymentByOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentProto          `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByOrderResponse) Reset() {
	*x = GetPaymentByOrderResponse{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByOrderResponse) ProtoMessage() {}

func (x *GetPaymentByOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByOrderResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentByOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentByOrderResponse) GetPayment() *PaymentProto {
	if x != nil {
		return x.Payment
	}
	return nil
}

// NotifyPayment is used by third-party payment providers to send async payment results
// (e.g. Alipay asynchronous notification callback).
type NotifyPaymentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PaymentId           int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status              PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payment.v1.PaymentStatus" json:"status,omitempty"`                         // SUCCESS or FAILED
	ProviderTradeNo     string                 `protobuf:"bytes,3,opt,name=provider_trade_no,json=providerTradeNo,proto3" json:"provider_trade_no,omitempty"`             // Transaction ID from the provider
	ProviderRawResponse string                 `protobuf:"bytes,4,opt,name=provider_raw_response,json=providerRawResponse,proto3" json:"provider_raw_response,omitempty"` // Full callback payload from the provider
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NotifyPaymentRequest) Reset() {
	*x = NotifyPaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaymentRequest) ProtoMessage() {}

func (x *NotifyPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaymentRequest.ProtoReflect.Descriptor instead.
func (*NotifyPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *NotifyPaymentRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *NotifyPaymentRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *NotifyPaymentRequest) GetProviderTradeNo() string {
	if x != nil {
		return x.ProviderTradeNo
	}
	return ""
}

func (x *NotifyPaymentRequest) GetProviderRawResponse() string {
	if x != nil {
		return x.ProviderRawResponse
	}
	return ""
}

type NotifyPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentProto          `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPaymentResponse) Reset() {
	*x = NotifyPaymentResponse{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaymentResponse) ProtoMessage() {}

func (x *NotifyPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaymentResponse.ProtoReflect.Descriptor instead.
func (*NotifyPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyPaymentResponse) GetPayment() *PaymentProto {
	if x != nil {
		return x.Payment
	}
	return nil
}

type AdminListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // 0 = all
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentsRequest) Reset() {
	*x = AdminListPaymentsRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentsRequest) ProtoMessage() {}

func (x *AdminListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*AdminListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{11}
}

func (x *AdminListPaymentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminListPaymentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListPaymentsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminListPaymentsRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type AdminListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentProto        `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListPaymentsResponse) Reset() {
	*x = AdminListPaymentsResponse{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListPaymentsResponse) ProtoMessage() {}

func (x *AdminListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*AdminListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{12}
}

func (x *AdminListPaymentsResponse) GetPayments() []*PaymentProto {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *AdminListPaymentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1capi/payment/v1/payment.proto\x12\n" +
	"payment.v1\"\xbb\x03\n" +
	"\fPaymentProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12\x1f\n" +
	"\vpaid_amount\x18\x05 \x01(\x01R\n" +
	"paidAmount\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.payment.v1.PaymentStatusR\x06status\x121\n" +
	"\x06method\x18\a \x01(\x0e2\x19.payment.v1.PaymentMethodR\x06method\x12*\n" +
	"\x11provider_trade_no\x18\b \x01(\tR\x0fproviderTradeNo\x122\n" +
	"\x15provider_raw_response\x18\t \x01(\tR\x13providerRawResponse\x12\x1f\n" +
	"\vfail_reason\x18\n" +
	" \x01(\tR\n" +
	"failReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xa0\x01\n" +
	"\x14CreatePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\x121\n" +
	"\x06method\x18\x04 \x01(\x0e2\x19.payment.v1.PaymentMethodR\x06method\"K\n" +
	"\x15CreatePaymentResponse\x122\n" +
	"\apayment\x18\x01 \x01(\v2\x18.payment.v1.PaymentProtoR\apayment\"i\n" +
	"\x15ProcessPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x121\n" +
	"\x06method\x18\x02 \x01(\x0e2\x19.payment.v1.PaymentMethodR\x06method\"L\n" +
	"\x16ProcessPaymentResponse\x122\n" +
	"\apayment\x18\x01 \x01(\v2\x18.payment.v1.PaymentProtoR\apayment\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\"H\n" +
	"\x12GetPaymentResponse\x122\n" +
	"\apayment\x18\x01 \x01(\v2\x18.payment.v1.PaymentProtoR\apayment\"5\n" +
	"\x18GetPaymentByOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"O\n" +
	"\x19GetPaymentByOrderResponse\x122\n" +
	"\apayment\x18\x01 \x01(\v2\x18.payment.v1.PaymentProtoR\apayment\"\xc8\x01\n" +
	"\x14NotifyPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.payment.v1.PaymentStatusR\x06status\x12*\n" +
	"\x11provider_trade_no\x18\x03 \x01(\tR\x0fproviderTradeNo\x122\n" +
	"\x15provider_raw_response\x18\x04 \x01(\tR\x13providerRawResponse\"K\n" +
	"\x15NotifyPaymentResponse\x122\n" +
	"\apayment\x18\x01 \x01(\v2\x18.payment.v1.PaymentProtoR\apayment\"~\n" +
	"\x18AdminListPaymentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\"g\n" +
	"\x19AdminListPaymentsResponse\x124\n" +
	"\bpayments\x18\x01 \x03(\v2\x18.payment.v1.PaymentProtoR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*r\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tREFUNDING\x10\x04\x12\f\n" +
	"\bREFUNDED\x10\x05*U\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04MOCK\x10\x01\x12\n" +
	"\n" +
	"\x06ALIPAY\x10\x02\x12\x0e\n" +
	"\n" +
	"WECHAT_PAY\x10\x032\xa6\x04\n" +
	"\x0ePaymentService\x12T\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a!.payment.v1.CreatePaymentResponse\x12W\n" +
	"\x0eProcessPayment\x12!.payment.v1.ProcessPaymentRequest\x1a\".payment.v1.ProcessPaymentResponse\x12K\n" +
	"\n" +
	"GetPayment\x12\x1d.payment.v1.GetPaymentRequest\x1a\x1e.payment.v1.GetPaymentResponse\x12`\n" +
	"\x11GetPaymentByOrder\x12$.payment.v1.GetPaymentByOrderRequest\x1a%.payment.v1.GetPaymentByOrderResponse\x12T\n" +
	"\rNotifyPayment\x12 .payment.v1.NotifyPaymentRequest\x1a!.payment.v1.NotifyPaymentResponse\x12`\n" +
	"\x11AdminListPayments\x12$.payment.v1.AdminListPaymentsRequest\x1a%.payment.v1.AdminListPaymentsResponseB+Z)github.com/storm/myidea/api/payment/v1;v1b\x06proto3"

var (
	file_api_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_payment_v1_payment_proto_rawDescData []byte
)

func file_api_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_payment_v1_payment_proto_rawDescData
}

var file_api_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_payment_v1_payment_proto_goTypes = []any{
	(PaymentStatus)(0),                // 0: payment.v1.PaymentStatus
	(PaymentMethod)(0),                // 1: payment.v1.PaymentMethod
	(*PaymentProto)(nil),              // 2: payment.v1.PaymentProto
	(*CreatePaymentRequest)(nil),      // 3: payment.v1.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),     // 4: payment.v1.CreatePaymentResponse
	(*ProcessPaymentRequest)(nil),     // 5: payment.v1.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),    // 6: payment.v1.ProcessPaymentResponse
	(*GetPaymentRequest)(nil),         // 7: payment.v1.GetPaymentRequest
	(*GetPaymentResponse)(nil),        // 8: payment.v1.GetPaymentResponse
	(*GetPaymentByOrderRequest)(nil),  // 9: payment.v1.GetPaymentByOrderRequest
	(*GetPaymentByOrderResponse)(nil), // 10: payment.v1.GetPaymentByOrderResponse
	(*NotifyPaymentRequest)(nil),      // 11: payment.v1.NotifyPaymentRequest
	(*NotifyPaymentResponse)(nil),     // 12: payment.v1.NotifyPaymentResponse
	(*AdminListPaymentsRequest)(nil),  // 13: payment.v1.AdminListPaymentsRequest
	(*AdminListPaymentsResponse)(nil), // 14: payment.v1.AdminListPaymentsResponse
}
var file_api_payment_v1_payment_proto_depIdxs = []int32{
	0,  // 0: payment.v1.PaymentProto.status:type_name -> payment.v1.PaymentStatus
	1,  // 1: payment.v1.PaymentProto.method:type_name -> payment.v1.PaymentMethod
	1,  // 2: payment.v1.CreatePaymentRequest.method:type_name -> payment.v1.PaymentMethod
	2,  // 3: payment.v1.CreatePaymentResponse.payment:type_name -> payment.v1.PaymentProto
	1,  // 4: payment.v1.ProcessPaymentRequest.method:type_name -> payment.v1.PaymentMethod
	2,  // 5: payment.v1.ProcessPaymentResponse.payment:type_name -> payment.v1.PaymentProto
	2,  // 6: payment.v1.GetPaymentResponse.payment:type_name -> payment.v1.PaymentProto
	2,  // 7: payment.v1.GetPaymentByOrderResponse.payment:type_name -> payment.v1.PaymentProto
	0,  // 8: payment.v1.NotifyPaymentRequest.status:type_name -> payment.v1.PaymentStatus
	2,  // 9: payment.v1.NotifyPaymentResponse.payment:type_name -> payment.v1.PaymentProto
	2,  // 10: payment.v1.AdminListPaymentsResponse.payments:type_name -> payment.v1.PaymentProto
	3,  // 11: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	5,  // 12: payment.v1.PaymentService.ProcessPayment:input_type -> payment.v1.ProcessPaymentRequest
	7,  // 13: payment.v1.PaymentService.GetPayment:input_type -> payment.v1.GetPaymentRequest
	9,  // 14: payment.v1.PaymentService.GetPaymentByOrder:input_type -> payment.v1.GetPaymentByOrderRequest
	11, // 15: payment.v1.PaymentService.NotifyPayment:input_type -> payment.v1.NotifyPaymentRequest
	13, // 16: payment.v1.PaymentService.AdminListPayments:input_type -> payment.v1.AdminListPaymentsRequest
	4,  // 17: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.CreatePaymentResponse
	6,  // 18: payment.v1.PaymentService.ProcessPayment:output_type -> payment.v1.ProcessPaymentResponse
	8,  // 19: payment.v1.PaymentService.GetPayment:output_type -> payment.v1.GetPaymentResponse
	10, // 20: payment.v1.PaymentService.GetPaymentByOrder:output_type -> payment.v1.GetPaymentByOrderResponse
	12, // 21: payment.v1.PaymentService.NotifyPayment:output_type -> payment.v1.NotifyPaymentResponse
	14, // 22: payment.v1.PaymentService.AdminListPayments:output_type -> payment.v1.AdminListPaymentsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_payment_v1_payment_proto_init() }
func file_api_payment_v1_payment_proto_init() {
	if File_api_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_api_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_api_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_payment_v1_payment_proto = out.File
	file_api_payment_v1_payment_proto_goTypes = nil
	file_api_payment_v1_payment_proto_depIdxs = nil
}
